# Scope the SBOM to real package dependencies. The Lunar syft collector pip-installs
# deps into a temp dir for license detection; without this, syft also catalogs every
# installed file and bundled OS/PE binary as license-less SBOM entries, which tanks
# license coverage. Package catalogers (minus binary) keep the dependency signal clean.
select-catalogers:
  - package
  - "-binary"
